using PhotoStudio.Application.Bookings.CreateBooking;
using PhotoStudio.Application.Bookings.RecordInPersonPayment;
using PhotoStudio.Application.Bookings.RescheduleBooking;
using PhotoStudio.Application.Bookings.SignContractInPerson;
using PhotoStudio.Domain.Bookings;

namespace PhotoStudio.Api.Endpoints;

/// <summary>
/// HTTP body to create a booking.
/// </summary>
/// <param name="PhotographerId">Photographer identifier. Will come from the authenticated user once authentication exists.</param>
/// <param name="ClientName">Client name.</param>
/// <param name="ClientPhone">Client phone.</param>
/// <param name="PackageName">Package name.</param>
/// <param name="PackagePrice">Package price.</param>
/// <param name="Currency">ISO 4217 currency code, for example "CRC".</param>
/// <param name="SessionStart">Session start, with offset.</param>
/// <param name="SessionEnd">Session end, with offset.</param>
public sealed record CreateBookingRequest(
    Guid PhotographerId,
    string ClientName,
    string ClientPhone,
    string PackageName,
    decimal PackagePrice,
    string Currency,
    DateTimeOffset SessionStart,
    DateTimeOffset SessionEnd);

/// <summary>
/// HTTP body to register a contract signed in person or on paper.
/// </summary>
/// <param name="SignerName">Name of the client who signed.</param>
/// <param name="TemplateVersion">Contract template version.</param>
/// <param name="IsPaperContract">Whether the contract was signed on paper and photographed.</param>
public sealed record SignContractInPersonRequest(string SignerName, string TemplateVersion, bool IsPaperContract);

/// <summary>
/// HTTP body to record a payment received face to face.
/// </summary>
/// <param name="Amount">Received amount.</param>
/// <param name="Currency">ISO 4217 currency code.</param>
/// <param name="Method">Cash or SinpeMovil.</param>
/// <param name="IdempotencyKey">Key generated by the app; retries with the same key do not duplicate the payment.</param>
public sealed record RecordInPersonPaymentRequest(decimal Amount, string Currency, PaymentMethod Method, string IdempotencyKey);

/// <summary>
/// HTTP body to move a confirmed booking to another slot.
/// </summary>
/// <param name="SessionStart">New session start, with offset.</param>
/// <param name="SessionEnd">New session end, with offset.</param>
public sealed record RescheduleBookingRequest(DateTimeOffset SessionStart, DateTimeOffset SessionEnd);

/// <summary>
/// Maps HTTP request DTOs to application commands.
/// </summary>
public static class BookingRequestMappings
{
    /// <summary>
    /// Maps the create request to its command.
    /// </summary>
    /// <param name="request">HTTP body.</param>
    /// <returns>The command.</returns>
    public static CreateBookingCommand ToCommand(this CreateBookingRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);
        return new CreateBookingCommand(
            request.PhotographerId,
            request.ClientName,
            request.ClientPhone,
            request.PackageName,
            request.PackagePrice,
            request.Currency,
            request.SessionStart,
            request.SessionEnd);
    }

    /// <summary>
    /// Maps the sign-contract request to its command.
    /// </summary>
    /// <param name="request">HTTP body.</param>
    /// <param name="bookingId">Booking identifier from the route.</param>
    /// <returns>The command.</returns>
    public static SignContractInPersonCommand ToCommand(this SignContractInPersonRequest request, Guid bookingId)
    {
        ArgumentNullException.ThrowIfNull(request);
        return new SignContractInPersonCommand(bookingId, request.SignerName, request.TemplateVersion, request.IsPaperContract);
    }

    /// <summary>
    /// Maps the in-person payment request to its command.
    /// </summary>
    /// <param name="request">HTTP body.</param>
    /// <param name="bookingId">Booking identifier from the route.</param>
    /// <returns>The command.</returns>
    public static RecordInPersonPaymentCommand ToCommand(this RecordInPersonPaymentRequest request, Guid bookingId)
    {
        ArgumentNullException.ThrowIfNull(request);
        return new RecordInPersonPaymentCommand(bookingId, request.Amount, request.Currency, request.Method, request.IdempotencyKey);
    }

    /// <summary>
    /// Maps the reschedule request to its command.
    /// </summary>
    /// <param name="request">HTTP body.</param>
    /// <param name="bookingId">Booking identifier from the route.</param>
    /// <returns>The command.</returns>
    public static RescheduleBookingCommand ToCommand(this RescheduleBookingRequest request, Guid bookingId)
    {
        ArgumentNullException.ThrowIfNull(request);
        return new RescheduleBookingCommand(bookingId, request.SessionStart, request.SessionEnd);
    }
}
