using PhotoStudio.Domain.Bookings;

namespace PhotoStudio.Application.Bookings.RecordInPersonPayment;

/// <summary>
/// Command to record a payment received face to face (B5).
/// </summary>
/// <param name="PhotographerId">Authenticated photographer; the booking must belong to them.</param>
/// <param name="BookingId">Booking identifier.</param>
/// <param name="Amount">Received amount.</param>
/// <param name="Currency">ISO 4217 currency code.</param>
/// <param name="Method">Cash or SINPE Móvil.</param>
/// <param name="IdempotencyKey">Key generated by the app so retries from an offline queue are safe.</param>
public sealed record RecordInPersonPaymentCommand(
    Guid PhotographerId,
    Guid BookingId,
    decimal Amount,
    string Currency,
    PaymentMethod Method,
    string IdempotencyKey);
